name: Deploy to Vultr

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [ "eu", "us" ]

    steps:
      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.region == 'eu' && secrets.VULTR_IP || secrets.US_VULTR_IP }}
          username: root
          password: ${{ matrix.region == 'eu' && secrets.VULTR_PASSWORD || secrets.US_VULTR_PASSWORD }}
          script: |
            cd ageofhexes/ageofhexes-io
            git pull origin main
            npm ci
            npm run build
            pm2 restart all