name: Deploy to Vultr

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server:
          - name: "EU Server (Frankfurt)"
            ip: ${{ secrets.VULTR_IP }}
            password: ${{ secrets.VULTR_PASSWORD }}
          - name: "US Server (New York)"
            ip: ${{ secrets.US_VULTR_IP }}
            password: ${{ secrets.US_VULTR_PASSWORD }}

    steps:
      - name: SSH and Deploy to ${{ matrix.server.name }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.server.ip }}
          username: root
          password: ${{ matrix.server.password }}
          script: |
            cd ageofhexes/ageofhexes-io
            git pull origin main
            npm ci
            npm run build
            pm2 restart all